# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c51baa8a65f33a33dfc9f381e2076caba0799627ec81b2c5fb7d4dbb46fcf854ad0497dae468647592a9daf8a798b50532a9ff9372cf7a5193e124d8f0e875ab

test:
  secret_key_base: 6e6669fa40a6f99f9cec1675b55878680f525a69ab3cc51b4532a4b37539d9c8622388e30a451e41f0d1144ca53f35b4c36992269d85ce05e765555f8d2ffab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
